name: Build and Publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build